import { GymClass, Reservation, Membership, Member, User, Post, QuickLink, Group } from "./types";

// ─── Helpers ───────────────────────────────────────────────────────────────
function getMondayOfCurrentWeek(): Date {
  const today = new Date();
  const day = today.getDay(); // 0=Sun
  const diff = day === 0 ? -6 : 1 - day;
  const monday = new Date(today);
  monday.setDate(today.getDate() + diff);
  return monday;
}

function weekDate(dayOfWeek: number, weekOffset = 0): string {
  const monday = getMondayOfCurrentWeek();
  const d = new Date(monday);
  d.setDate(monday.getDate() + dayOfWeek + weekOffset * 7);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

// ─── Current User ──────────────────────────────────────────────────────────
export const currentUser: User = {
  id: "user-123",
  name: "Eduardo García",
  email: "eduardo@primaryperformance.mx",
  role: "admin",
};

// ─── Classes ───────────────────────────────────────────────────────────────
export const mockClasses: GymClass[] = [
  {
    id: "1",
    name: "Funcional 6am",
    serviceType: "group",
    dayOfWeek: 0,
    startTime: "06:00",
    endTime: "07:00",
    coach: "Juan Pérez",
    maxCapacity: 20,
    reservedCount: 12,
    status: "active",
  },
  {
    id: "2",
    name: "Crossfit 7am",
    serviceType: "group",
    dayOfWeek: 0,
    startTime: "07:00",
    endTime: "08:00",
    coach: "María García",
    maxCapacity: 15,
    reservedCount: 15,
    status: "active",
  },
  {
    id: "3",
    name: "Yoga Flow",
    serviceType: "group",
    dayOfWeek: 1,
    startTime: "18:00",
    endTime: "19:00",
    coach: "Carlos López",
    maxCapacity: 25,
    reservedCount: 8,
    status: "active",
    note: "Llevar mat y toalla",
  },
  {
    id: "4",
    name: "Pilates 9am",
    serviceType: "group",
    dayOfWeek: 2,
    startTime: "09:00",
    endTime: "10:00",
    coach: "Laura Martínez",
    maxCapacity: 20,
    reservedCount: 6,
    status: "active",
  },
  {
    id: "5",
    name: "HIIT 5pm",
    serviceType: "group",
    dayOfWeek: 2,
    startTime: "17:00",
    endTime: "18:00",
    coach: "Juan Pérez",
    maxCapacity: 18,
    reservedCount: 18,
    status: "active",
  },
  {
    id: "6",
    name: "Kinesio 10am",
    serviceType: "kinesiology",
    dayOfWeek: 2,
    startTime: "10:00",
    endTime: "11:00",
    coach: "Dr. Ramírez",
    maxCapacity: 4,
    reservedCount: 2,
    status: "active",
    note: "Sesión de rehabilitación",
  },
  {
    id: "7",
    name: "Funcional 6am",
    serviceType: "group",
    dayOfWeek: 3,
    startTime: "06:00",
    endTime: "07:00",
    coach: "María García",
    maxCapacity: 20,
    reservedCount: 14,
    status: "active",
  },
  {
    id: "8",
    name: "Boxing 7pm",
    serviceType: "group",
    dayOfWeek: 3,
    startTime: "19:00",
    endTime: "20:00",
    coach: "Carlos López",
    maxCapacity: 16,
    reservedCount: 12,
    status: "active",
  },
  {
    id: "9",
    name: "Zumba 6pm",
    serviceType: "group",
    dayOfWeek: 4,
    startTime: "18:00",
    endTime: "19:00",
    coach: "Laura Martínez",
    maxCapacity: 30,
    reservedCount: 19,
    status: "active",
  },
  {
    id: "10",
    name: "Spinning 7am",
    serviceType: "group",
    dayOfWeek: 5,
    startTime: "07:00",
    endTime: "08:00",
    coach: "Juan Pérez",
    maxCapacity: 20,
    reservedCount: 7,
    status: "active",
  },
  {
    id: "11",
    name: "Stretching 5pm",
    serviceType: "group",
    dayOfWeek: 5,
    startTime: "17:00",
    endTime: "18:00",
    coach: "María García",
    maxCapacity: 25,
    reservedCount: 3,
    status: "active",
  },
];

// ─── Reservations ──────────────────────────────────────────────────────────
export let mockReservations: Reservation[] = [
  // Current user – this week
  {
    id: "res-1",
    classId: "1",
    studentId: "user-123",
    studentName: "Eduardo García",
    studentEmail: "eduardo@primaryperformance.mx",
    classDate: weekDate(0),
    status: "reserved",
  },
  {
    id: "res-2",
    classId: "4",
    studentId: "user-123",
    studentName: "Eduardo García",
    studentEmail: "eduardo@primaryperformance.mx",
    classDate: weekDate(2),
    status: "reserved",
  },
  // Other students – Mon Funcional
  {
    id: "res-3",
    classId: "1",
    studentId: "user-001",
    studentName: "Ana Rodríguez",
    studentEmail: "ana@gmail.com",
    classDate: weekDate(0),
    status: "attended",
  },
  {
    id: "res-4",
    classId: "1",
    studentId: "user-002",
    studentName: "Carlos Herrera",
    studentEmail: "carlos@gmail.com",
    classDate: weekDate(0),
    status: "attended",
  },
  {
    id: "res-5",
    classId: "1",
    studentId: "user-003",
    studentName: "María López",
    studentEmail: "maria@gmail.com",
    classDate: weekDate(0),
    status: "reserved",
  },
  {
    id: "res-6",
    classId: "1",
    studentId: "user-004",
    studentName: "Roberto Sánchez",
    studentEmail: "roberto@gmail.com",
    classDate: weekDate(0),
    status: "absent",
  },
  // Wed Pilates
  {
    id: "res-7",
    classId: "4",
    studentId: "user-001",
    studentName: "Ana Rodríguez",
    studentEmail: "ana@gmail.com",
    classDate: weekDate(2),
    status: "reserved",
  },
  {
    id: "res-8",
    classId: "4",
    studentId: "user-005",
    studentName: "Sofía Morales",
    studentEmail: "sofia@gmail.com",
    classDate: weekDate(2),
    status: "absent",
  },
  // Thu Boxing
  {
    id: "res-9",
    classId: "8",
    studentId: "user-002",
    studentName: "Carlos Herrera",
    studentEmail: "carlos@gmail.com",
    classDate: weekDate(3),
    status: "reserved",
  },
  {
    id: "res-10",
    classId: "8",
    studentId: "user-004",
    studentName: "Roberto Sánchez",
    studentEmail: "roberto@gmail.com",
    classDate: weekDate(3),
    status: "reserved",
  },
];

// ─── Memberships ───────────────────────────────────────────────────────────
export let mockMemberships: Membership[] = [
  {
    id: "mem-1",
    studentId: "user-123",
    studentName: "Eduardo García",
    studentEmail: "eduardo@primaryperformance.mx",
    serviceType: "group",
    plan: "mensual",
    paymentStatus: "paid",
    membershipStatus: "active",
    amount: 1200,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
  },
  {
    id: "mem-2",
    studentId: "user-001",
    studentName: "Ana Rodríguez",
    studentEmail: "ana@gmail.com",
    serviceType: "group",
    plan: "trimestral",
    paymentStatus: "paid",
    membershipStatus: "active",
    amount: 3200,
    startDate: "2026-03-01",
    endDate: "2026-05-31",
  },
  {
    id: "mem-3",
    studentId: "user-002",
    studentName: "Carlos Herrera",
    studentEmail: "carlos@gmail.com",
    serviceType: "group",
    plan: "mensual",
    paymentStatus: "overdue",
    membershipStatus: "expired",
    amount: 1200,
    startDate: "2026-03-01",
    endDate: "2026-03-31",
  },
  {
    id: "mem-4",
    studentId: "user-003",
    studentName: "María López",
    studentEmail: "maria@gmail.com",
    serviceType: "group",
    plan: "semestral",
    paymentStatus: "paid",
    membershipStatus: "active",
    amount: 6500,
    startDate: "2026-01-01",
    endDate: "2026-06-30",
  },
  {
    id: "mem-5",
    studentId: "user-004",
    studentName: "Roberto Sánchez",
    studentEmail: "roberto@gmail.com",
    serviceType: "group",
    plan: "mensual",
    paymentStatus: "pending",
    membershipStatus: "pending",
    amount: 1200,
    startDate: "2026-04-15",
    endDate: "2026-05-14",
  },
  {
    id: "mem-6",
    studentId: "user-005",
    studentName: "Sofía Morales",
    studentEmail: "sofia@gmail.com",
    serviceType: "group",
    plan: "anual",
    paymentStatus: "paid",
    membershipStatus: "active",
    amount: 12000,
    startDate: "2026-01-01",
    endDate: "2026-12-31",
  },
  // Eduardo tiene también kinesio — demuestra múltiples membresías por usuario
  {
    id: "mem-7",
    studentId: "user-123",
    studentName: "Eduardo García",
    studentEmail: "eduardo@primaryperformance.mx",
    serviceType: "kinesiology",
    plan: "mensual",
    paymentStatus: "paid",
    membershipStatus: "active",
    amount: 800,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    coachName: "Dr. Ramírez",
  },
  // María López también tiene kinesio
  {
    id: "mem-8",
    studentId: "user-003",
    studentName: "María López",
    studentEmail: "maria@gmail.com",
    serviceType: "kinesiology",
    plan: "mensual",
    paymentStatus: "paid",
    membershipStatus: "active",
    amount: 800,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    coachName: "Dr. Ramírez",
  },
];

// ─── Members ───────────────────────────────────────────────────────────────
export let mockMembers: Member[] = [
  {
    id: "user-123",
    name: "Eduardo García",
    email: "eduardo@primaryperformance.mx",
    role: "admin",
    status: "active",
    contractedServices: ["group", "kinesiology"],
  },
  {
    id: "user-001",
    name: "Ana Rodríguez",
    email: "ana@gmail.com",
    role: "member",
    status: "active",
    assignedCoachId: "coach-001",
    assignedCoachName: "Juan Pérez",
    contractedServices: ["group"],
  },
  {
    id: "user-002",
    name: "Carlos Herrera",
    email: "carlos@gmail.com",
    role: "member",
    status: "inactive",
    contractedServices: ["group"],
  },
  {
    id: "user-003",
    name: "María López",
    email: "maria@gmail.com",
    role: "member",
    status: "active",
    assignedCoachId: "coach-005",
    assignedCoachName: "Dr. Ramírez",
    contractedServices: ["group", "kinesiology"],
  },
  {
    id: "user-004",
    name: "Roberto Sánchez",
    email: "roberto@gmail.com",
    role: "member",
    status: "active",
    contractedServices: ["group"],
  },
  {
    id: "user-005",
    name: "Sofía Morales",
    email: "sofia@gmail.com",
    role: "member",
    status: "active",
    assignedCoachId: "coach-001",
    assignedCoachName: "Juan Pérez",
    contractedServices: ["group", "personal_training"],
  },
  {
    id: "coach-001",
    name: "Juan Pérez",
    email: "juan@primaryperformance.mx",
    role: "coach",
    status: "active",
    contractedServices: ["group", "personal_training"],
  },
  {
    id: "coach-002",
    name: "María García",
    email: "mgarcia@primaryperformance.mx",
    role: "coach",
    status: "active",
    contractedServices: ["group"],
  },
  {
    id: "coach-003",
    name: "Carlos López",
    email: "clopez@primaryperformance.mx",
    role: "coach",
    status: "active",
    contractedServices: ["group"],
  },
  {
    id: "coach-004",
    name: "Laura Martínez",
    email: "laura@primaryperformance.mx",
    role: "coach",
    status: "active",
    contractedServices: ["group"],
  },
  {
    id: "coach-005",
    name: "Dr. Ramírez",
    email: "ramirez@primaryperformance.mx",
    role: "coach",
    status: "active",
    contractedServices: ["kinesiology"],
  },
];

// ─── Community ─────────────────────────────────────────────────────────────
export const mockQuickLinks: QuickLink[] = [
  { label: "Calendario semanal", href: "/calendar" },
  { label: "Gestión de clases", href: "/admin/classes" },
  { label: "Lista de miembros", href: "/admin/members" },
  { label: "Control de membresías", href: "/admin/memberships" },
];

export const mockGroups: Group[] = [
  { id: "g1", name: "Morning Team", emoji: "🌅" },
  { id: "g2", name: "HIIT Group", emoji: "🔥" },
  { id: "g3", name: "Kinesio", emoji: "🏥" },
];

const _now = Date.now();

export let mockPosts: Post[] = [
  {
    id: "post-1",
    authorId: "coach-001",
    authorName: "Juan Pérez",
    authorRole: "coach",
    createdAt: new Date(_now - 2 * 3_600_000).toISOString(),
    content:
      "Buenos días equipo 💪 Mañana hay clase especial de HIIT a las 6am. Vengan con toda la energía — va a ser una sesión intensa. ¡Los espero!",
    likesCount: 8,
    comments: [
      {
        id: "c1",
        authorId: "user-001",
        authorName: "Ana Rodríguez",
        authorRole: "member",
        content: "Ahí estaré! 🔥",
        createdAt: new Date(_now - 1.5 * 3_600_000).toISOString(),
      },
      {
        id: "c2",
        authorId: "user-003",
        authorName: "María López",
        authorRole: "member",
        content: "Yo también voy!",
        createdAt: new Date(_now - 3_600_000).toISOString(),
      },
    ],
  },
  {
    id: "post-2",
    authorId: "user-123",
    authorName: "Eduardo García",
    authorRole: "admin",
    createdAt: new Date(_now - 5 * 3_600_000).toISOString(),
    content:
      "📊 Resultado de la semana: 85% de asistencia en clases grupales. Excelente trabajo a toda la comunidad Primary Performance. ¡Sigamos así! 🏋️",
    likesCount: 12,
    comments: [
      {
        id: "c3",
        authorId: "coach-002",
        authorName: "María García",
        authorRole: "coach",
        content: "Muy buenos números, felicitaciones a todos!",
        createdAt: new Date(_now - 4 * 3_600_000).toISOString(),
      },
    ],
  },
  {
    id: "post-3",
    authorId: "user-123",
    authorName: "Eduardo García",
    authorRole: "admin",
    createdAt: new Date(_now - 24 * 3_600_000).toISOString(),
    content:
      "⚠️ Aviso: el área de kinesio estará en mantenimiento este jueves de 10am a 12pm. Las sesiones de ese horario se reprogramarán. Los contactamos por separado.",
    likesCount: 5,
    comments: [],
  },
  {
    id: "post-4",
    authorId: "coach-002",
    authorName: "María García",
    authorRole: "coach",
    createdAt: new Date(_now - 2 * 24 * 3_600_000).toISOString(),
    content:
      "Nuevo plan de entrenamiento funcional para abril ya disponible. Este mes nos enfocamos en fuerza de core y movilidad. ¡Va a ser un mes increíble! 🎯",
    likesCount: 15,
    comments: [
      {
        id: "c4",
        authorId: "user-005",
        authorName: "Sofía Morales",
        authorRole: "member",
        content: "Justo lo que necesitaba, gracias María!",
        createdAt: new Date(_now - 1.9 * 24 * 3_600_000).toISOString(),
      },
    ],
  },
];
